### ISSUE TITLE
The training data is missing

### ISSUE THREAD

**Issue by ABadCandy** [stathius/wave_propagation#1]
Hi, I want to reproduce your experiments but can't download data from box
![image](https://user-images.githubusercontent.com/19199003/69546175-2f54fd00-0fce-11ea-89f3-8cdb9c6f02fa.png)
and I generate some data by generate.py but how should I organize them into the format that the code needs? Could you tell me more details or upload the original data again, thanks.

**Comment by stathius** [comment]
Hey, thanks for pointing this out.
The box link was not made public. 
Please try again and let me know if it doesn't work.

**Comment by ABadCandy** [comment]
@stathius Sorry for not responding in time because of some other things. I have tried to download it again, but still failed and disconnected after a while. So could you please upload a copy "data_new.tar.gz" to Google Cloud Disk too? Many thanks!

**Comment by stathius** [comment]
@ABadCandy This is really strange. Are you using this link? https://imperialcollegelondon.app.box.com/s/hj1o82rwj8shlqekf2iyugo5u0ow50hz

 I've checked with others and the link works with them. What is exactly the problem? Unfortunately I don't have enough quota in google drive to support that long term.
I could give a look at onedrive, let me get back to you about that.

**Comment by ABadCandy** [comment]
@stathius yes, I used that link to download the data. 
The problem is that it would interrupt after a while and say  "Failed - file not found".  And I'm not sure if it's a network or the box‘s server issue. 
Onedrive is also a good alternative, looking forward to it.
